name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install prospector\[with_everything\] pre-commit --no-cache-dir

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run prospector
        run: prospector
